# Generated by Django 5.0.8 on 2024-08-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
